eureka:
  client:
    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true
server:
  port: 9999
spring:
  application:
    name: client-app
  mvc:
    view:
      prefix: /WEB-INF/pages/
      suffix: .jsp