eureka:
  client:
    instance:
      preferAddress: true
    seriveurl:
      defaultZone: http//localhost:8761/eureka
server:
  port: 8088
spring:
  application:
    name: adminService
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/admin_db
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: true
